# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import config_service_pb2 as config__service__pb2
from . import interopt_service_pb2 as interopt__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in interopt_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InteroptServiceStub(object):
    """Extending the ConfigurationService by creating a new service that includes both old and new RPCs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunConfiguration = channel.unary_unary(
                '/InteroptService/RunConfiguration',
                request_serializer=config__service__pb2.ConfigurationRequest.SerializeToString,
                response_deserializer=config__service__pb2.ConfigurationResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/InteroptService/Shutdown',
                request_serializer=config__service__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=config__service__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.SetupStudy = channel.unary_unary(
                '/InteroptService/SetupStudy',
                request_serializer=interopt__service__pb2.SetupStudyRequest.SerializeToString,
                response_deserializer=interopt__service__pb2.SetupStudyResponse.FromString,
                _registered_method=True)
        self.GetStudy = channel.unary_unary(
                '/InteroptService/GetStudy',
                request_serializer=interopt__service__pb2.GetStudyRequest.SerializeToString,
                response_deserializer=interopt__service__pb2.GetStudyResponse.FromString,
                _registered_method=True)
        self.UpdateStudy = channel.unary_unary(
                '/InteroptService/UpdateStudy',
                request_serializer=interopt__service__pb2.UpdateStudyRequest.SerializeToString,
                response_deserializer=interopt__service__pb2.UpdateStudyResponse.FromString,
                _registered_method=True)


class InteroptServiceServicer(object):
    """Extending the ConfigurationService by creating a new service that includes both old and new RPCs
    """

    def RunConfiguration(self, request, context):
        """Include all RPCs from the original ConfigurationService
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupStudy(self, request, context):
        """New RPC function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStudy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InteroptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.RunConfiguration,
                    request_deserializer=config__service__pb2.ConfigurationRequest.FromString,
                    response_serializer=config__service__pb2.ConfigurationResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=config__service__pb2.ShutdownRequest.FromString,
                    response_serializer=config__service__pb2.ShutdownResponse.SerializeToString,
            ),
            'SetupStudy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupStudy,
                    request_deserializer=interopt__service__pb2.SetupStudyRequest.FromString,
                    response_serializer=interopt__service__pb2.SetupStudyResponse.SerializeToString,
            ),
            'GetStudy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudy,
                    request_deserializer=interopt__service__pb2.GetStudyRequest.FromString,
                    response_serializer=interopt__service__pb2.GetStudyResponse.SerializeToString,
            ),
            'UpdateStudy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStudy,
                    request_deserializer=interopt__service__pb2.UpdateStudyRequest.FromString,
                    response_serializer=interopt__service__pb2.UpdateStudyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InteroptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('InteroptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InteroptService(object):
    """Extending the ConfigurationService by creating a new service that includes both old and new RPCs
    """

    @staticmethod
    def RunConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InteroptService/RunConfiguration',
            config__service__pb2.ConfigurationRequest.SerializeToString,
            config__service__pb2.ConfigurationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InteroptService/Shutdown',
            config__service__pb2.ShutdownRequest.SerializeToString,
            config__service__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetupStudy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InteroptService/SetupStudy',
            interopt__service__pb2.SetupStudyRequest.SerializeToString,
            interopt__service__pb2.SetupStudyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InteroptService/GetStudy',
            interopt__service__pb2.GetStudyRequest.SerializeToString,
            interopt__service__pb2.GetStudyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStudy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/InteroptService/UpdateStudy',
            interopt__service__pb2.UpdateStudyRequest.SerializeToString,
            interopt__service__pb2.UpdateStudyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
